version: '3'
services:
  prereq:
    build: ../prereq
    entrypoint: bash -c 'exit 0'
  libqb:
    image: compose_prereq
    depends_on:
      - prereq
    working_dir: /tmp
    command: >
      bash -c 'wget --no-check-certificate https://github.com/ClusterLabs/libqb/releases/download/v0.17.2/libqb-0.17.2.tar.xz &&
               tar Jxvf libqb-0.17.2.tar.xz &&
               cd /tmp/libqb-0.17.2 &&
               ./autogen.sh &&
               ./configure --prefix=/opt/cluster &&
               make -j`grep -c ^processor /proc/cpuinfo` &&
               mkdir -pv /tmp/build /tmp/deb &&
               make install DESTDIR=/tmp/build &&
               fpm -s dir -t deb -n cluster-libqb -v 0.17.2 -C /tmp/build -p /tmp/deb &&
               cp /tmp/deb/* /exhaust/'
    volumes:
      - './exhaust:/exhaust'
  corosync:
    image: compose_prereq
    depends_on:
      - libqb
    working_dir: /tmp
    command: >
      bash -c 'wget --no-check-certificate https://github.com/corosync/corosync/releases/download/v2.4.5/corosync-2.4.5.tar.gz &&
               tar zxvf corosync-2.4.5.tar.gz &&
               cd /tmp/corosync-2.4.5 &&
               dpkg -i /exhaust/* &&
               ./autogen.sh &&
               PATH="/opt/cluster/bin:$PATH" PKG_CONFIG_PATH="/opt/cluster/lib/pkgconfig" ./configure \
               --prefix=/opt/cluster \
               --bindir=/opt/cluster/bin \
               --libdir=/opt/cluster/lib \
               --sysconfdir=/etc \
               --localstatedir=/var &&
               make -j`grep -c ^processor /proc/cpuinfo` &&
               mkdir -pv /tmp/build /tmp/deb &&
               make install DESTDIR=/tmp/build &&
               fpm -s dir -t deb -n cluster-corosync -v 2.4.5 -C /tmp/build -p /tmp/deb -d cluster-libqb &&
               cp /tmp/deb/* /exhaust/'
    volumes:
      - './exhaust:/exhaust'
  cglue:
    build: ../cluster-glue
    depends_on:
      - corosync
    working_dir: /tmp
    command: >
      bash -c 'wget --no-check-certificate https://github.com/ClusterLabs/cluster-glue/archive/glue-1.0.12.tar.gz &&
               tar zxvf glue-1.0.12.tar.gz &&
               cd /tmp/cluster-glue-glue-1.0.12 &&
               dpkg -i /exhaust/* &&
               ./autogen.sh &&
               PATH="/opt/cluster/bin:$PATH" PKG_CONFIG_PATH="/opt/cluster/lib/pkgconfig" ./configure \
               --enable-fatal-warnings=no \
               --prefix=/opt/cluster \
               --bindir=/opt/cluster/bin \
               --libdir=/opt/cluster/lib \
               --sysconfdir=/etc \
               --localstatedir=/var &&
               make -j`grep -c ^processor /proc/cpuinfo` &&
               mkdir -pv /tmp/build /tmp/deb &&
               make install DESTDIR=/tmp/build &&
               fpm -s dir -t deb -n cluster-glue -v 1.0.12 -C /tmp/build -p /tmp/deb -d cluster-libqb -d cluster-corosync &&
               cp /tmp/deb/* /exhaust/'
    volumes:
      - './exhaust:/exhaust'
